# Generated by Django 2.2 on 2019-08-07 12:18

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cover_image',
            field=models.ImageField(default='books/empty_cover.jpg/', upload_to=polls.models.cover_upload_path),
        ),
    ]
