# Generated by Django 2.2 on 2019-08-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='cover_image',
        ),
    ]
