# Generated by Django 2.1 on 2019-07-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0004_auto_20190725_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='books/empty_cover.jpg/', upload_to='books/'),
        ),
    ]
